### ISSUE TITLE
Did you manage to get plausible results?

### ISSUE THREAD

**Issue by ascust** [leffff/adversarial-diffusion-distillation#1]

**Comment by leffff** [comment]
Hi, so far I am limited in compute, therefore I am waiting to soon get my hands on more powerful GPUs. Right now I only have RTX 4090, which is not enough

**Comment by digbangbang** [comment]
Hi, the paper says that the step size of the teacher model is set to 1. I think this is unreasonable. I tried to use ddpm CIFAR10 to conduct ADD experiments. When the teacher model step size is 1, sampling is performed, and the result is a picture of completely random noise.

**Comment by leffff** [comment]
answered here https://github.com/Stability-AI/generative-models/issues/238

> Hi, the paper says that the step size of the teacher model is set to 1. I think this is unreasonable. I tried to use ddpm CIFAR10 to conduct ADD experiments. When the teacher model step size is 1, sampling is performed, and the result is a picture of completely random noise.

**Comment by akasharidas** [comment]
We have a working implementation and training code for Latent Adversarial Diffusion Distillation, and achieved good results with multiple base models and resolutions: https://github.com/AMD-AIG-AIMA/AMD-Diffusion-Distillation
