### ISSUE TITLE
teacher error?

### ISSUE THREAD

**Issue by GuangtaoLyu** [leffff/adversarial-diffusion-distillation#2]
![image](https://github.com/leffff/adversarial-diffusion-distillation/assets/57834464/5e55607c-f375-43f8-9827-3a5fdf8e5039)
        
xt, t = forward_diffusion_process(x, noise_scheduler, num_timesteps=num_teacher_timesteps)

according to the paper, it should start from the student output x_beta?

xt, t = forward_diffusion_process(x_beta, noise_scheduler, num_timesteps=num_teacher_timesteps)

**Comment by leffff** [comment]
Thanks! you are right!
fixed https://github.com/leffff/adversarial-diffusion-distillation/commit/e85182fcce388a4ffa696fae7e7c6e9b083d9389
